### ISSUE TITLE
Code highlight feels strange

### ISSUE THREAD

**Issue by axl411** [stephenwzl/hexo-theme-eleme#1]
See this: https://stephenwzl.github.io/hexo-theme-eleme/2016/02/12/详解-iOS-8-UIPresentationController-custom-presentation/

**Comment by stephenwzl** [comment]
i'll 考虑 integrate `highlight.js`

**Comment by stephenwzl** [comment]
@axl411 highlight已更正，配色问题将在未来feature改进
